return function(TestConsole)
	TestConsole.output("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu nisl mauris.")
	TestConsole.ask("Ut at commodo massa?")
	TestConsole.output("Aenean nec tellus est.")
	TestConsole.ask("Sed faucibus tincidunt suscipit?")
	TestConsole.output("Duis in enim ac arcu semper euismod. Integer nec cursus neque.")
	TestConsole.ask("Nam eget elit in lectus semper placerat?")
	TestConsole.output("Pellentesque a pulvinar nisi. Morbi maximus sit amet dolor at blandit.")
	TestConsole.ask("Curabitur nisl erat, accumsan tempus pretium vel, consequat id purus?")
	TestConsole.output("Goodbye")
end
