return function(TestConsole)
	TestConsole.output("Proin accumsan sapien orci, eget hendrerit purus ullamcorper a.")
	TestConsole.ask("Morbi id cursus orci?")
	TestConsole.output("In non lacus vel ante ullamcorper cursus vel nec nisl.")
	TestConsole.ask("Nunc tincidunt lacus sed dui elementum, facilisis pulvinar odio scelerisque?")
	TestConsole.output("Integer nibh ligula, auctor id nisl id, luctus posuere mi.")
	TestConsole.ask("Integer consequat lobortis enim ut iaculis?")
	TestConsole.output("Mauris id vestibulum mi. Vestibulum eget odio mi.")
	TestConsole.ask("Phasellus id ex vel arcu ullamcorper faucibus?")
	TestConsole.output("Goodbye")
end
