return function(TestConsole)
	TestConsole.output("\nHello")
	TestConsole.ask("This should yield")
	TestConsole.output("\nWorld")
	TestConsole.ask("This should yield")
	TestConsole.output("\nHello")
	TestConsole.ask("This should yield")
	TestConsole.output("\nWorld")
	TestConsole.ask("This should yield")
	TestConsole.output("\nGoodbye")
end
